
stable_diffusion:
  model_path: runwayml/stable-diffusion-v1-5

filter_model:
  fairface: weights/fairface/res34_fair_align_multi_4_20190809.pt
  threshold: 0.6
  transformations:
    Resize:
      size: [224, 224]
    Normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

generation:
  image_latents: data/ffhq_latents
  output_folder: attribute_images
  cross_replace_steps: 1.0
  self_replace_steps: 0.6
  attribute_class: race
  attributes: [with white skin, with black skin, with asian appearance, with indian appearance]
  num_samples: 300

rtpt:
  experiment_name: Attribute_Variation
  name_initials: XX
