---
seed: 0

model:
  architecture: resnet101
  num_classes: 500
  pretrained: true

dataset:
  type: celeba_identities
  validation_set_size: 0
  image_size: 224
  root: data/celeba
  attribute_group: gender

transformations:
  RandomHorizontalFlip:
    p: 0.5
  RandomResizedCrop:
    size: [224, 224]
    scale: [0.8, 1]
    ratio: [0.8, 1.25]

optimizer:
  SGD:
    lr: 0.1
    momentum: 0.9

lr_scheduler:
  MultiStepLR:
    milestones: [80, 90]
    gamma: 0.1

training:
  num_epochs: 100
  batch_size: 128
  dataloader_num_workers: 16
  save_path: results/
  robust_training: true

rtpt:
  experiment_name: Training target classifier
  name_initials: XX

wandb:
  enable_logging: true
  args:
    project: Targets_Gender_Appearance
    name: ResNet101_CelebA_Gender_Robust
    save_code: true